name: Trigger AWS CodeBuild

on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Start CodeBuild Project
        run: |
          aws codebuild start-build --project-name plugins_zenerp_app_br_build